services:
  gopigo3-ros2:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: gopigo3-ros2
    container_name: gopigo3-ros2
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      # Force Fast DDS to use UDPv4 for transport
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # ===================================================================
      # ANPASSUNG FÜR GUI-WEITERLEITUNG (NUR EINEN BLOCK AKTIVIEREN)
      # ===================================================================

      # --- Block 1: Für Linux ODER Windows 11 mit WSLg ---
      # WSLg leitet die DISPLAY Variable automatisch weiter.
      #- DISPLAY=${DISPLAY}

      # --- Block 2: Für Windows 10 mit VcXsrv ODER macOS mit XQuartz ---
      - DISPLAY=host.docker.internal:0

      # ======== bleibt immer an ===========================================
      - QT_X11_NO_MITSHM=1

    volumes:
      # Mountet den Quellcode-Ordner
      - ./ros2ws:/home/rosdev/ros2_ws
      # Mount the custom DDS configuration
      #- ./udp_transport.xml:/etc/cyclonedds/udp_transport.xml

      # ===================================================================
      # ANPASSUNG FÜR GUI-WEITERLEITUNG (VOLUMES)
      # ===================================================================

      # --- Nur für Linux notwendig! ---
      # Für Windows und macOS auskommentiert lassen.
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw
      
      # ===================================================================

    stdin_open: true
    tty: true
    network_mode: "host"